# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rapidmcp._generated import mcp_v2_pb2 as mcp__v2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpStub(object):
    """RapidMCP protocol v2 — MCP 2026-07-28 semantics over gRPC.
    Stateless: every request carries its own RequestMeta; nothing is inferred
    from earlier requests on the same connection.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/mcp.v2.Mcp/Discover',
                request_serializer=mcp__v2__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=mcp__v2__pb2.DiscoverResult.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/mcp.v2.Mcp/ListTools',
                request_serializer=mcp__v2__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcp__v2__pb2.ListToolsResult.FromString,
                _registered_method=True)
        self.ListResources = channel.unary_unary(
                '/mcp.v2.Mcp/ListResources',
                request_serializer=mcp__v2__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=mcp__v2__pb2.ListResourcesResult.FromString,
                _registered_method=True)
        self.ListResourceTemplates = channel.unary_unary(
                '/mcp.v2.Mcp/ListResourceTemplates',
                request_serializer=mcp__v2__pb2.ListResourceTemplatesRequest.SerializeToString,
                response_deserializer=mcp__v2__pb2.ListResourceTemplatesResult.FromString,
                _registered_method=True)
        self.ListPrompts = channel.unary_unary(
                '/mcp.v2.Mcp/ListPrompts',
                request_serializer=mcp__v2__pb2.ListPromptsRequest.SerializeToString,
                response_deserializer=mcp__v2__pb2.ListPromptsResult.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/mcp.v2.Mcp/Complete',
                request_serializer=mcp__v2__pb2.CompleteRequest.SerializeToString,
                response_deserializer=mcp__v2__pb2.CompleteResult.FromString,
                _registered_method=True)


class McpServicer(object):
    """RapidMCP protocol v2 — MCP 2026-07-28 semantics over gRPC.
    Stateless: every request carries its own RequestMeta; nothing is inferred
    from earlier requests on the same connection.
    """

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResourceTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrompts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=mcp__v2__pb2.DiscoverRequest.FromString,
                    response_serializer=mcp__v2__pb2.DiscoverResult.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=mcp__v2__pb2.ListToolsRequest.FromString,
                    response_serializer=mcp__v2__pb2.ListToolsResult.SerializeToString,
            ),
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=mcp__v2__pb2.ListResourcesRequest.FromString,
                    response_serializer=mcp__v2__pb2.ListResourcesResult.SerializeToString,
            ),
            'ListResourceTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResourceTemplates,
                    request_deserializer=mcp__v2__pb2.ListResourceTemplatesRequest.FromString,
                    response_serializer=mcp__v2__pb2.ListResourceTemplatesResult.SerializeToString,
            ),
            'ListPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrompts,
                    request_deserializer=mcp__v2__pb2.ListPromptsRequest.FromString,
                    response_serializer=mcp__v2__pb2.ListPromptsResult.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=mcp__v2__pb2.CompleteRequest.FromString,
                    response_serializer=mcp__v2__pb2.CompleteResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.v2.Mcp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.v2.Mcp', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mcp(object):
    """RapidMCP protocol v2 — MCP 2026-07-28 semantics over gRPC.
    Stateless: every request carries its own RequestMeta; nothing is inferred
    from earlier requests on the same connection.
    """

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v2.Mcp/Discover',
            mcp__v2__pb2.DiscoverRequest.SerializeToString,
            mcp__v2__pb2.DiscoverResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v2.Mcp/ListTools',
            mcp__v2__pb2.ListToolsRequest.SerializeToString,
            mcp__v2__pb2.ListToolsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v2.Mcp/ListResources',
            mcp__v2__pb2.ListResourcesRequest.SerializeToString,
            mcp__v2__pb2.ListResourcesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResourceTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v2.Mcp/ListResourceTemplates',
            mcp__v2__pb2.ListResourceTemplatesRequest.SerializeToString,
            mcp__v2__pb2.ListResourceTemplatesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v2.Mcp/ListPrompts',
            mcp__v2__pb2.ListPromptsRequest.SerializeToString,
            mcp__v2__pb2.ListPromptsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v2.Mcp/Complete',
            mcp__v2__pb2.CompleteRequest.SerializeToString,
            mcp__v2__pb2.CompleteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
